# Generated by Django 3.2.25 on 2024-11-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_url'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdata',
            options={'verbose_name_plural': 'Sales data'},
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='user',
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='added_to_cart',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
