# Generated by Django 3.2.25 on 2024-11-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20241114_1009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
    ]
